server:
  port: 8888
  
spring:
  mvc:
    static-path-pattern: /**
    view:
      suffix: .html
      prefix: /
  resources:
    static-locations: 
      classpath:/resources/,
      classpath:/static/,
      classpath:/public/
  servlet:
    multipart:
      enabled: true
      max-file-size: 300MB
      max-request-size: 300MB
#文件存储路径
prop:
  upload-folder: ./files/
  download-folder: F:/download/
  download-file: file.zip


